### ISSUE TITLE
Нейминг переменных

### ISSUE THREAD

**Issue by Red-Cat-Fat** [slupok/BeeClicker#1]
Придерживайся одного стиля наименования переменных.
https://github.com/slupok/BeeClicker/blob/5a419570d8bacae9fe66bb3a19cc84ce25d0e558/Clicker/Assets/Scripts/AutoMove.cs#L9-L12
Например, приватные переменные называй с маленькой буквы и нижним подчёркиванием, вроде _variableName.
Локальные просто с маленькой буквы localVariableName.
А публичные с большой PublicVariableName

**Comment by slupok** [comment]
https://github.com/slupok/BeeClicker/commit/ca78df3d7deeff3f1ec83e2368e5376e317386d6
