### ISSUE TITLE
Лишний финт ушами

### ISSUE THREAD

**Issue by Red-Cat-Fat** [slupok/BeeClicker#10]
Логика работы понятна, но имя не подходящее. Если 
возвращаешь bool, то и название функции должно быть соответствующим. Но вообще в данном случае вообще лучше перейти на систему подписки на смерть "монстра". 
То есть когда кликают на монстра вызывать AddClick, но ничего не возвращать: https://github.com/slupok/BeeClicker/blob/5a419570d8bacae9fe66bb3a19cc84ce25d0e558/Clicker/Assets/Scripts/Monster.cs#L38-L50
А доработать вот этот кусок кода:
https://github.com/slupok/BeeClicker/blob/5a419570d8bacae9fe66bb3a19cc84ce25d0e558/Clicker/Assets/Scripts/Click.cs#L41-L47
Чтобы то, что под if выполнялось при смерти юнита. OnDestroy тебе зачем?

**Comment by slupok** [comment]
https://github.com/slupok/BeeClicker/commit/ef62030328ba4842a55cf8d2f083b8484b93766f
