### ISSUE TITLE
Рефлексия - зло

### ISSUE THREAD

**Issue by Red-Cat-Fat** [slupok/BeeClicker#11]
Переименуешь метод, а тут спавн будет пытаться вызвать по старому названию.
https://github.com/slupok/BeeClicker/blob/5a419570d8bacae9fe66bb3a19cc84ce25d0e558/Clicker/Assets/Scripts/Spawn.cs#L28

**Comment by slupok** [comment]
https://github.com/slupok/BeeClicker/commit/4e054b2ebd0b9485996e54b5d1e1fefc5fc3bed1
