### ISSUE TITLE
Бесполезный компонент

### ISSUE THREAD

**Issue by Red-Cat-Fat** [slupok/BeeClicker#12]
Вроде уже писал тебе в ишшуре к другому классу, где использовал нормаль, но повторюсь ещё раз, что можно отслеживать нормаль пересечения объекта по коллизии. Так что этот метод песполезен
https://github.com/slupok/BeeClicker/blob/5a419570d8bacae9fe66bb3a19cc84ce25d0e558/Clicker/Assets/Scripts/Wall.cs#L7

**Comment by slupok** [comment]
https://github.com/slupok/BeeClicker/commit/1e40d00535c8fbcd558c40d393f9b65ab029d20d
