### ISSUE TITLE
Сразу всё

### ISSUE THREAD

**Issue by Red-Cat-Fat** [slupok/BeeClicker#14]
1. Не закрывай Issues пока не проверили.
2. Запомни, что рефлексию использовать нельзя.
3. Нет необходимости приводить к типу тот же самый тип. Почитай как работают компоненты
4. Вообще нет проверки на null.

**Comment by slupok** [comment]
3. Почему?

**Comment by slupok** [comment]
3. Почему? В моем примере:
`Monster obj = hit.collider.gameObject.GetComponent<Monster>() as Monster
if(obj != null && obj.AddClick())
{
//..
}`
Тут же идет проверка на клик по монстру. Например, если мы кликнем на стену(на которой нет нужного компонента), то в obj будет null,  а без приведения вылезет исключение. Даже документация советует так делать. https://docs.unity3d.com/ScriptReference/GameObject.GetComponent.html
Или я не так понял проблему?

**Comment by slupok** [comment]
ааа, или это к обобщенному GetComponent не нужно приводить, тогда к необобщенным нужно?

**Comment by Red-Cat-Fat** [comment]
hit.collider.gameObject.GetComponent<Monster>() - ты уже получаешь какой-то компонент.
Это может быть Monster, а может быть AlphaMonster или BetaMonster (которые наследуются от класса Monster). Если тебе нужен будет использовать компоненты именно как Monster, то приведение типов корректно. Если же тебе без разницы (как в данном случае, который ты привёл) то это лишние операции.
Если на объекте не висит никаких компонентов типа Monster, то результат будет null.

**Comment by slupok** [comment]
2. https://github.com/slupok/BeeClicker/commit/327906d0a9a8d6a1c5e6e09b29c6f31bd1bdec28

**Comment by slupok** [comment]
2. Забыл добавить новые файлы

**Comment by slupok** [comment]
2. https://github.com/slupok/BeeClicker/commit/738da66beeb802fef34b9531bc8d50655d742d15
В чем плохо GetComponent?

**Comment by slupok** [comment]
3. https://github.com/slupok/BeeClicker/commit/663846d8928d76d700a77d7a3fa770ed20917880

**Comment by slupok** [comment]
4. https://github.com/slupok/BeeClicker/commit/fd605e1ca635efca9fddf764e3d68f582100ab45
я так понял всегда нужно делать проверку на null объектов полученных с компонентов?

**Comment by slupok** [comment]
Вопрос: 
При спавне учитываются стены, если я не собираюсь изменять размеры стен, как будет лучше: 
1)как сделал я, отнимать размер стены, где размер стены я задаю фактически константой.
2)отнимать размер стены, где размер будет все таки вычисляться динамически.
3)создать на сцене объект, его размеры будут определять область спавна и ничего отнимать не надо.

**Comment by Red-Cat-Fat** [comment]
Вообще зависит от условий, я если честно не очень хорошо помню твой код (я их много проверил)
Но вообще нужно просто задать область самого спавна. Так как область должна соответствовать разрешению экрана, то необходимо вычислить пропорции и соотношение сторон в процессе игры. И в рамках этой зоны уже спавнить объекты.
GetComponent не плох сам по себе. Он плох, когда результат его вывода используется без проверки на null.
А проверку на null нужно делать там, где null реально может вылезти случайно. То есть в ситуациях, когда ты берёшь из неизвестного тебе (в рамках выполняемого кода) места. Другими словами если переменная имеет атрибут [SerializeField] или публичная, то достаточно проверить её в Awake и если она пуста - выдать Debug.LogError() для дизов, чтобы они всё поправили. 
Причём это относится и к public, которые используешь для задачи переменных из инспектора.
И отсюда вытекает ещё 1 момент. Если тебе не нужно использовать переменную вне этого класса - не делай её public. Делай приватной с атрибутом SerializeField.
И то! Что гласит один из столпов ООП - инкапсуляция?
