### ISSUE TITLE
Доработать gitignore 

### ISSUE THREAD

**Issue by Red-Cat-Fat** [slupok/BeeClicker#15]
Добавь в gitignore .idea и прочий генерируемый хлам. 
Либо коммить выборочно, только то, что меняешь в коде и что важно.
Очень затрудняет чтение комитов всякие конфиги IDE.

**Comment by slupok** [comment]
6cadf0e19197d5f7c9181e0e14a2474fa77a8881

**Comment by Red-Cat-Fat** [comment]
Под выборочно я имел ввиду не каждую строчку в отдельности, а смотреть что ты комитишь в гит. Например, коммит "поправил NRE" и комитишь только те файлы, где этот NRE поправил. А ты просто добавляешь сразу все изменения в коммит и это добавляет сложности к читабельности

**Comment by slupok** [comment]
Я понял, но это уже со следующими коммитами
