### ISSUE TITLE
Вероятный NRE

### ISSUE THREAD

**Issue by Red-Cat-Fat** [slupok/BeeClicker#2]
Не рассмотрен случай, если триггер сработает не на стену, а на что-то другое.
https://github.com/slupok/BeeClicker/blob/5a419570d8bacae9fe66bb3a19cc84ce25d0e558/Clicker/Assets/Scripts/AutoMove.cs#L24-L29

**Comment by Red-Cat-Fat** [comment]
По коду много подобного рода проблем. Не видел ни одной проверки на null

**Comment by slupok** [comment]
https://github.com/slupok/BeeClicker/commit/ca78df3d7deeff3f1ec83e2368e5376e317386d6

**Comment by slupok** [comment]
https://github.com/slupok/BeeClicker/commit/476f7398280f29a14ec9e037942ba34db6b82e7e
