### ISSUE TITLE
Проблемы с перемещением

### ISSUE THREAD

**Issue by Red-Cat-Fat** [slupok/BeeClicker#3]
Да это работает, но я бы использовал Rigidbody.velocity. Макар будет вам рассказывать на следующей лекции более подробно как, что и почему.
Так же, если ты не используешь скорость в векторе Move, то тогда операцию Move.normalized можно сделать только 1 раз при инициализации.
https://github.com/slupok/BeeClicker/blob/5a419570d8bacae9fe66bb3a19cc84ce25d0e558/Clicker/Assets/Scripts/AutoMove.cs#L32-L35

**Comment by slupok** [comment]
Не исправленно. Не проходили?

**Comment by slupok** [comment]
https://github.com/slupok/BeeClicker/commit/5a27dd6689c93dea1c9bd143c8deb43cdea34c8d Исправил
