### ISSUE TITLE
А?

### ISSUE THREAD

**Issue by Red-Cat-Fat** [slupok/BeeClicker#4]
Это куда более жёсткие проблемы с неймингом, чет кодстайл. Всегда именуй переменные так, чтобы была понятна их суть. Да ещё и тут 1 общее имя для разных сущностей.
https://github.com/slupok/BeeClicker/blob/5a419570d8bacae9fe66bb3a19cc84ce25d0e558/Clicker/Assets/Scripts/Click.cs#L9
https://github.com/slupok/BeeClicker/blob/5a419570d8bacae9fe66bb3a19cc84ce25d0e558/Clicker/Assets/Scripts/Click.cs#L41

**Comment by slupok** [comment]
исправлено

**Comment by Red-Cat-Fat** [comment]
Где коммит?
