### ISSUE TITLE
Нужно меньше GetComponent

### ISSUE THREAD

**Issue by Red-Cat-Fat** [slupok/BeeClicker#5]
Зачем постоянно брать GetComponent, если это можно это сделать только 1 раз? Или вовсе сделать ссылку на соответствующий компонент. Более того такой подход череват NRE.
https://github.com/slupok/BeeClicker/blob/5a419570d8bacae9fe66bb3a19cc84ce25d0e558/Clicker/Assets/Scripts/Click.cs#L45-L46
Более того, Text.text = "new value" не есть хорошая практика. Если хочешь использовать UI - заведи отдельный компонент, который будет рулить работой с UI. Посмотри как в примере с пчёлкой

**Comment by slupok** [comment]
https://github.com/slupok/BeeClicker/commit/ef62030328ba4842a55cf8d2f083b8484b93766f
