### ISSUE TITLE
Не держи ненужные комментарии

### ISSUE THREAD

**Issue by Red-Cat-Fat** [slupok/BeeClicker#6]
Коментарии в целом зло - нужно писать такой код, чтобы всё было понятно и без комментариев, за счёт нейминга и адекватной механики обработки данных. Но тут просто ненужный кусок кода. Гит для того и нужен, чтобы откатить изменения в случае чего и посмотреть как оно там было.
https://github.com/slupok/BeeClicker/blob/5a419570d8bacae9fe66bb3a19cc84ce25d0e558/Clicker/Assets/Scripts/Click.cs#L40

**Comment by slupok** [comment]
исправлено
