### ISSUE TITLE
Static переменные в логике игры - зло

### ISSUE THREAD

**Issue by Red-Cat-Fat** [slupok/BeeClicker#7]
Никогда не используй статичные переменные, особенно в логике игры. Есть случаи, когда нужны статичные методы, но статичные переменные не стоит использовать вообще(как и паттерн одиночка). Это чревато опасностями при работе с большими проектами, когда один программист поправил стат.переменную по своей логике, а другой по другой. И вот мучайтесь во время дебага, когда переменная используется в 100500 местах.
https://github.com/slupok/BeeClicker/blob/5a419570d8bacae9fe66bb3a19cc84ce25d0e558/Clicker/Assets/Scripts/Click.cs#L14-L15

**Comment by slupok** [comment]
https://github.com/slupok/BeeClicker/commit/ef62030328ba4842a55cf8d2f083b8484b93766f

**Comment by Red-Cat-Fat** [comment]
Тут та же история с рефлексией
