### ISSUE TITLE
Делегируй задачи тем классам, которые ими занимаются

### ISSUE THREAD

**Issue by Red-Cat-Fat** [slupok/BeeClicker#8]
В данном случае, если поражения вычисляются в Monster.cs, то почему эта переменная тут?
Заведи отдельный "менеджер" который будет отсчитывать эти параметры. Посмотри как в пчёлке устроен Score.
https://github.com/slupok/BeeClicker/blob/5a419570d8bacae9fe66bb3a19cc84ce25d0e558/Clicker/Assets/Scripts/Click.cs#L17-L22

**Comment by slupok** [comment]
Добавил Score.cs 
https://github.com/slupok/BeeClicker/commit/ef62030328ba4842a55cf8d2f083b8484b93766f

**Comment by Red-Cat-Fat** [comment]
Рефлексия - хуже синглтона. Я же ставил тебе ишуу на запрет использования рефлексии

**Comment by Red-Cat-Fat** [comment]
И не закрывай ишуы пока не проверили
