### ISSUE TITLE
Лишние пустые строки

### ISSUE THREAD

**Issue by Red-Cat-Fat** [slupok/BeeClicker#9]
Не критично, но некрасиво. Пустая строка на 24 строке. Разделение пустыми строками обоснованы, но только если несут в себе логический смысл
https://github.com/slupok/BeeClicker/blob/5a419570d8bacae9fe66bb3a19cc84ce25d0e558/Clicker/Assets/Scripts/Monster.cs#L22-L35

**Comment by slupok** [comment]
Исправлено
